export const CAREERS = [
  {
    position: 'Senior Frontend Engineer',
    company: 'Yellow Systems',
    logo: '/images/careers/Yellow.jpg',
    location: 'United States',
    location_type: 'Remote',
    type: 'Fulltime',
    start_date: 'Mar 2020',
    end_date: 'Mar 2023',
    link: 'https://yellow.systems/',
  },
  {
    position: 'Full Stack Engineer',
    company: 'Oxley Enterprises, Inc ',
    logo: '/images/careers/Oxley.jpg',
    location: 'United States',
    location_type: 'Remote',
    type: 'Fulltime',
    start_date: 'Feb 2017',
    end_date: 'Feb 2020',
    link: 'https://www.oxleyenterprises.com/',
  },
  {
    position: 'Frontend Developer',
    company: 'QUAPE PTE LTD',
    logo: '/images/careers/Quape.jpg',
    location: 'Singapore',
    location_type: 'On-site',
    type: 'Fulltime',
    start_date: 'Oct 2015',
    end_date: 'Jan 2017',
    link: 'https://www.quape.com/',
  },
  {
    position: "Bachelor's Degree",
    company: 'Tsinghua University',
    logo: '/images/careers/Univ.jpg',
    location: '',
    location_type: '',
    type: '',
    start_date: 'Sep 2011',
    end_date: 'Sep 2015',
    link: '',
  },
];
